name : CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast:false
      matrix:
        os:[windows-latest]
        python-version:
          - "3.12-dev"
  
    name:Test
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout coe
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies
        run: python -m pip install --upgrade pip
             pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover -s tests -p '*_test.py'